name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # spécifiez votre version de Python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest  # remplacez par votre commande de test
      - name: Build Docker image
        run: |
          docker build -t eya2554/flaskapp .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
           username: ${{ secrets.DOCKER_USERNAME }}  # Utilisation du secret
           password: ${{ secrets.DOCKER_PASSWORD }}  # Utilisation du secret
      - name: Push to another Docker registry
      run: |
        docker tag eya2554/appflask eya2554/appflask:latest
        docker push eya2554/appflask:latest