name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        continue-on-error: true  # Only for debugging
      - name: Run tests
        run: |
          pytest
        continue-on-error: true  # Only for debugging
        - name: Push to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_Paris210824!@ }}" | docker login -u "${{ secrets.DOCKER_eya2554 }}" --password-stdin
          docker build -t ton_nom_utilisateur/FlaskApp .
          docker push ton_nom_utilisateur/FlaskApp

