name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # spécifiez votre version de Python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest  # remplacez par votre commande de test
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_eya2554 }}  # Assurez-vous que cela correspond à votre secret renommé
          password: ${{ secrets.DOCKER_Paris210824!@ }}  # Assurez-vous que cela correspond à votre secret renommé

      - name: Build and tag Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_eya2554 }}/flaskapp:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_eya2554 }}/flaskapp:latest
